[versions]
agp = "8.1.3"
poi = "5.2.3"

[libraries]
poi = { group = "org.apache.poi", name = "poi", version.ref = "poi" }
poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version.ref = "poi" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }